name: screwdriver_ur10e

image_shape: &image_shape [3, 224, 384]
action_shape: &action_shape [7]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    cam_front:
      shape: *image_shape
      type: rgb
    qpos:
      shape: *action_shape
      type: low_dim
  action:
    shape: *action_shape

dataset:
  _target_: dataset.dataset2d.Dataset2D
  dataset_path: data/screwdriver_ur10e.h5
  horizon: ${horizon}
  n_obs_steps: ${n_obs_steps}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}//2'}
  input_meta: 
    obs:
      cam_front: *image_shape
      qpos: *action_shape
    action: *action_shape
  mask_head: False
  use_mem: True
  
