defaults:
  - _self_
  - task: default_task

name: ${task.name}
task_name: ${task.name}
shape_meta: ${task.shape_meta}

seed: 42

horizon: 32
n_obs_steps: 3
n_action_steps: 32
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy:
  _target_: policy.dp2_dino.DP2

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    # variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample

  obs_encoder:
    _target_: model.vision.multi_image_obs_encoder_dino.MultiImageObsEncoder
    shape_meta: ${shape_meta}
    weights_path: "weights/dinov3_vits16_pretrain_lvd1689m-08c60483.pth"

  optimazer_cfg: ${optimizer}
  scheduler_cfg: ${lr_scheduler}
  
  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 10
  obs_as_global_cond: ${obs_as_global_cond}
  # diffusion_step_embed_dim: 256
  diffusion_step_embed_dim: 128
  # down_dims: [512, 1024, 2048]
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True

ema:
  update_after_steps: 1000

dataloader:
  train:
    batch_size: 128
    num_workers: 4
    shuffle: True
    pin_memory: True
  val:
    batch_size: 128
    num_workers: 4
    shuffle: False
    pin_memory: False

optimizer:
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

lr_scheduler:
  scheduler: cosine
  warmup_steps: 500

checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/loss
  mode: min
  save_top_k: 1
  save_last: True
  save_weights_only: True
  every_n_train_steps: null
  save_on_train_epoch_end: False
  filename: 'step={step:08d}-loss={val/loss:.4f}'
  auto_insert_metric_name: False

trainer:
  max_steps: 100_000
  accelerator: auto
  devices: auto
  precision: 32
  val_check_interval: 10_000
  check_val_every_n_epoch: null
  enable_progress_bar: True

logging:
  project: DP2-DINO
  mode: offline
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}
  tags: ["${task_name}"]
  id: null
  group: null

multi_run:
  run_dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}

hydra:
  job:
    override_dirname: ${task_name}
  run:
    dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
  sweep:
    dir: outputs/${logging.project}/${now:%Y.%m.%d.%H.%M.%S}_${task_name}
    subdir: ${hydra.job.num}
